server:
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %l %u %t \"%r\" %s %b %D %{X-Forwarded-For}i %{X-Forwarded-Proto}i %{X-Forwarded-Port} %{Location}o"
    basedir: ${TOMCAT_BASEDIR_ROOT:/tmp}/${spring.application.name}_${server.port}

logging:
  level:
    root: INFO
    com.netflix.discovery: WARN

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}
      registryFetchIntervalSeconds: 10 # 30 for production?
  instance:
    leaseRenewalIntervalInSeconds: 10 # should be set to 30 for production
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

security:
  require-ssl: false
  ignored:
    - "/env"
    - "/mappings"
    - "/trace"

management:
  security:
    enabled: false

# settings used by Spring
spring:
  main:
    banner-mode: OFF

---
spring:
  profiles: h2

  datasource:
    url: jdbc:h2:mem:tempdb;MODE=oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa

  jpa:
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: ""
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

flyway:
  enabled: true
  locations: db/migration/h2

---
spring:
  profiles: mysql

  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

flyway:
  enabled: true
  locations: db/migration/mysql
