# the application uses cloud config
# the values here are only used during testing

server:
  port: 8120
security:
  require-ssl: false
  ignored:
    - "/**"

cors.allow.origin: "*"

# default to h2 database
spring:
  profiles:
    include: h2

nfs:
  ccms:
    card-customer-service:
      endpoint-url: http://localhost:9092/CardCustomerService

---
spring:
  profiles: mysql

  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost/carddb}
    username: cardsvc
    password: password

