# the application uses cloud config
# the values here are only used during testing

server:
  port: 8120
security:
  require-ssl: false
  ignored:
    - "/**"

management:
  security:
    enabled: false


cors.allow.origin: "*"

logging:
  level:
    root: INFO
    org.apache.http: WARN
    com.netflix: WARN
    org.springframework.security: INFO
    com.netflix.discovery.DiscoveryClient: OFF

# default to h2 database
spring:
  profiles:
    include: h2

nfs:
  ccms:
    card-customer-service:
      endpoint-url: http://localhost:9092/CardCustomerService

---
spring:
  profiles: mysql

  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost/carddb}
    username: cardsvc
    password: password

